### ISSUE TITLE
offset error in DB.class.php's query_update

### ISSUE THREAD

**Issue by arifulalam** [jayaneetha/PDO#1]
Hello,
While running your code/project offset error showing on **DB.class.php** script's 169, 170, 171 line which are:

``` php
    $where_field = $where[0];
    $where_operator = $where[1];
    $where_value = $where[2];
```

When I changed those to

``` php
    $where_field = (!empty($where[0])) ? $where[0] : '';
    $where_operator = (!empty($where[1])) ? $where[1] : '';
    $where_value = (!empty($where[2])) ? $where[2] : '';
```

there is no error showing.

Will you check please.

Regards

**Comment by jayaneetha** [comment]
Thanks for reminding. I'll update that thing.
